config/routes.rb
Rails.application.routes.draw do


  ### Root routing #####
  #root 'test_controller#index'
  #root 'demo#index'
  root :to => 'public#index'

  #get 'public/show'
  get 'show/:permalink', :to => 'public#show'

  get 'admin', :to => 'access#menu' #note if user is already logged in go to the menu, otherwise it auto goes to login screen
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resource :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete  #need to add delete if we want a delete page.
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  #match defaults from ruby, don't need them
  #get 'subjects/index'
  #get 'subjects/show'
  #get 'subjects/new'
  #get 'subjects/edit'
  #get 'subjects/delete'

  ### routes for the test_controller######
  #get 'test_controller/index'
  get ':controller(/:action(/:id))'

  ### routes for the demo controller##### #simple match route
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
  #also removing default route bc/ it make go away in future versions of rails
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'admin'

  #note this will block all actions if user isn't logged in, i.e. menu,login,attempt_login,logout, ect.
  before_action :confirm_logged_in, :except => [:login,:attempt_login,:logout]
  #blocks menu   --> white list approach.

  def menu
    #display text & links
  end

  def login
    #login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      #authorized user is an object from AdminUser table
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are now logged in."
      redirect_to(admin_path)
    else
      flash.now[:notice] = "Invalid username/password combination"
      render('login')
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to(access_login_path)
  end

  private



end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= text_field_tag(:username, params[:username]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In") %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class = "identity">Logged in as:</div>
  <ul>
    <li><%= link_to("Manage Subjects",subjects_path) %></li>
    <li><%= link_to("Manage Pages",pages_path) %></li>
    <li><%= link_to("Manage Sections",sections_path) %></li>
    <li><%= link_to("Manage Admin Users",'#') %></li>
    <!-- note the path helper doesnt work here....   access_logout_path -->
    <li><%= link_to("Logout", access_logout_path) %></li>
  </ul>
</div>