config/routes.rb
Rails.application.routes.draw do


  ### Root routing #####
  #root 'test_controller#index'
  #root 'demo#index'
  root :to => 'public#index'

  #get 'public/show'
  get 'show/:permalink', :to => 'public#show'

  get 'admin', :to => 'access#menu' #note if user is already logged in go to the menu, otherwise it auto goes to login screen
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resource :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete  #need to add delete if we want a delete page.
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  #match defaults from ruby, don't need them
  #get 'subjects/index'
  #get 'subjects/show'
  #get 'subjects/new'
  #get 'subjects/edit'
  #get 'subjects/delete'

  ### routes for the test_controller######
  #get 'test_controller/index'
  get ':controller(/:action(/:id))'

  ### routes for the demo controller##### #simple match route
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
  #also removing default route bc/ it make go away in future versions of rails
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.erb
<%= error_messages_for(f.object) %>  <!-- Using application helper here, renders in helper -->

<table summary = "Page from fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Subject</th>
    <td><%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}) %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
<tr>
  <th>Visible</th>
  <td><%= f.check_box(:visible) %></td>
</tr>
</table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back_link') %>

<div class="page delete">
  <h2>Delete Page</h2>

  <!-- you MUST have :method, but URL can be omitted -->
  <%= form_for(@page, :method => 'delete') do |f| %>
      <p> Are you sure you want to permanently delete this subject?</p>
      <p class="reference-name"><%= f.object.name %></p>

      <div class="form-buttons">
        <%= f.submit("Delete Page") %>
      </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back_link') %>

<div class="pages edit">
  <h2>Update Pages</h2>

  <!-- form_for(@subject, :url => subject_path(@subject), :method => 'patch') do |f|
  could do it like this. but better to use helpers.
  -->
  <%= form_for(@page) do  |f| %>

      <!-- inserting partial for this loop -->
      <%= render(:partial => 'form', :locals => {:f => f}) %>
      <!-- end of partial -->

      <div class="form_buttons">
        <%= f.submit("Update Page") %>
      </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<% @page_title = "All Pages" %>
<div class="pages index">
  <h2>Pages</h2>
  <!-- could just use subjects/new but url helper is better -->
  <%= link_to("Add New Page", new_page_path, :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Subject ID</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
        <tr>
          <td><%= page.position %></td>
          <td><%= page.subject_id %></td>
          <td><%= page.name %></td>
          <td><%= page.permalink %></td>
          <!-- ternary opeator, short hand for if else statement. -->
          <td class="center"><%= page.visible ? 'Yes' : 'No' %></td>

          <td class="actions">
            <!-- using resourceful url helpers subject_path(subject)-->
            <%= link_to("Show", page_path(page), :class => 'action show') %>
            <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
            <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back_link') %>

<div class="pages new">
  <h2>Create Pages</h2>
  <%= form_for(@page) do  |f| %>

      <%= render(:partial => 'form', :locals => {:f => f}) %>

      <div class="form_buttons">
        <%= f.submit("Create Page") %>
      </div>
  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Subject</h2>

  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
    <tr>
      <th>Subject ID</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>



</div>