config/routes.rb
Rails.application.routes.draw do


  ### Root routing #####
  #root 'test_controller#index'
  #root 'demo#index'
  root :to => 'public#index'

  #get 'public/show'
  get 'show/:permalink', :to => 'public#show'

  get 'admin', :to => 'access#menu' #note if user is already logged in go to the menu, otherwise it auto goes to login screen
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resource :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete  #need to add delete if we want a delete page.
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  #match defaults from ruby, don't need them
  #get 'subjects/index'
  #get 'subjects/show'
  #get 'subjects/new'
  #get 'subjects/edit'
  #get 'subjects/delete'

  ### routes for the test_controller######
  #get 'test_controller/index'
  get ':controller(/:action(/:id))'

  ### routes for the demo controller##### #simple match route
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
  #also removing default route bc/ it make go away in future versions of rails
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord

  #Relationships
  has_many :pages

  #define some scopes (Queries defined in model)
  #scopes (queries are run when they are called)

  #Visible subjects
  scope :visible, lambda { where(:visible => true) }
  #Non visible subjects
  scope :invisible, lambda { where(:visible => false)}

  scope :sorted, lambda {order("position ASC")}
  scope :newest_first, lambda {order("created_at DESC")}

  #note query may be coming from user, so therefore we need to sanitize the user
  #input, in this case query
  scope :search, lambda {|query| where (["name LIKE ?", "%#{query}%"])}

  #this forces something to be entered for name
  validates_presence_of :name
  validates_length_of :name, :maximum => 255

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  #define layout in views -> layouts
  layout 'admin'

  before_action :confirm_logged_in

  def index
    #this is using the named scope
    logger.debug("**** DEBUG --> subjects controller - index *****")
    @subjects = Subject.sorted
    #it then looks for the index action
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    #form is expecting a subject object to create
    @subject = Subject.new({:name => 'Default'})
    @subject_count = Subject.count + 1
  end

  def create
    #this renders the create template

    #Instantiate a new object using form parameters
    @subject = Subject.new(subject_params)
    #save the object
    if @subject.save
      #If save succeeds, redirect to the index action
      flash[:notice] = "subject created successfully."
      redirect_to(subjects_path)
    else
      @subject_count = Subject.count + 1 #incase update fails, and 'new stub re-rendered, not new controller'
      render('new') #this just re-renders the form template
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    #Find a new object using parameters
    @subject = Subject.find(params[:id])
    #Update the object
    if @subject.update_attributes(subject_params())
      #If save succeeds, redirect to the index action
      flash[:notice] = "Subject updated successfully."
      redirect_to(subject_path(@subject))
    else
      render('edit') #this just re-renders the form template
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    #remember the object is still "avaliable to rails right after deletion"
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully."
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end


end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>  <!-- Using application helper here, renders in helper -->
<table summary = "Subject from fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Created</th>
    <td><%= f.datetime_select(:created_at, :order=> [:month,:day,:year]) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back_link') %>

<div class="subject delete">
  <h2>Delete subject</h2>

  <!-- you MUST have :method, but URL can be omitted -->
  <%= form_for(@subject, :method => 'delete') do |f| %>
  <p> Are you sure you want to permanently delete this subject?</p>
  <p class="reference-name"><%= f.object.name %></p>

  <div class="form-buttons">
    <%= f.submit("Delete Subject") %>
  </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back_link') %>

<div class="subjects edit">
  <h2>Update Subjects</h2>

  <!-- form_for(@subject, :url => subject_path(@subject), :method => 'patch') do |f|
  could do it like this. but better to use helpers.
  -->
  <%= form_for(@subject) do  |f| %>

      <!-- render the _form partial -->
      <%= render(:partial => 'form', :locals => {:f => f}) %>

      <div class="form_buttons">
        <%= f.submit("Update Subject") %>
      </div>
  <% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title = "All Subjects" %>
<div class="subjects index">
  <h2>Subjects</h2>
  <!-- could just use subjects/new but url helper is better -->
  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
  <% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.position %></td>
    <td><%= subject.name %></td>
    <!-- ternary opeator, short hand for if else statement. -->
    <td class="center"><%= status_tag(subject.visible)%></td>
    <td class="center"><%= subject.pages.size %></td>
    <td class="actions">
      <!-- using resourceful url helpers subject_path(subject)-->
      <%= link_to("Show", subject_path(subject), :class => 'action show') %>
      <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
      <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
    </td>
  </tr>
  <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back_link') %>

<div class="subjects new">
  <h2>Create Subjects</h2>

  <%= form_for(@subject) do  |f| %>
      <!-- don't need the _  needs the f variable so must pass it to the partial (f) -->
  <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form_buttons">
    <%= f.submit("Create Subject") %>
  </div>
  <% end %>
</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>



</div>