config/routes.rb
Rails.application.routes.draw do


  ### Root routing #####
  #root 'test_controller#index'
  #root 'demo#index'
  root :to => 'public#index'

  #get 'public/show'
  get 'show/:permalink', :to => 'public#show'

  get 'admin', :to => 'access#menu' #note if user is already logged in go to the menu, otherwise it auto goes to login screen
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resource :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete  #need to add delete if we want a delete page.
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  #match defaults from ruby, don't need them
  #get 'subjects/index'
  #get 'subjects/show'
  #get 'subjects/new'
  #get 'subjects/edit'
  #get 'subjects/delete'

  ### routes for the test_controller######
  #get 'test_controller/index'
  get ':controller(/:action(/:id))'

  ### routes for the demo controller##### #simple match route
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
  #also removing default route bc/ it make go away in future versions of rails
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password

  #for legacy databases, crazy named database.
  #self.table_name = "admin_users"
  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits

  EMAIL_REGEX = /\a[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  FORBIDDEN_USERNAMES = ['fuck','shit','cunt']

  validates :first_name, :presence => true,
            :length => {:maximum => 25}
  #validates_presence_of :first_name
  #validates_length_of :first_name, :maximum => 25
  validates :last_name, :presence => true,
            :length => {:maximum => 50}
  #validates_presence_of :last_name
  #validates_length_of :last_name, :maximum => 50
  #validates_presence_of :username
  #validates_length_of :username, :within => 8..25
  #validates_uniqueness_of :username
  validates :username, :length => {:within => 8..25},
            :uniqueness => true

  validates :email, :presence => true,
            :length => { :maximum => 50},
            :uniqueness => {:with => EMAIL_REGEX},
            :confirmation => true
  #long form validations
  #validates_presence_of :email
  #validates_length_of :email, :maximum => 100
  #validates_format_of :email, :with => EMAIL_REGEX
  #validates_confirmation_of :email

  validate :username_is_allowed
  validate :no_new_users_on_monday, :on => :create


  scope :sorted, lambda {order('last_name ASC,first_name ASC')}
  def name
    "#{first_name} #{last_name}"
  end

  private

  def username_is_allowed
    if FORBIDDEN_USERNAMES.include?(username)
      errors.add(:username, "has been restricted from user.")
    end
  end

  def no_new_users_on_monday
    if Time.now.wday == 6 || Time.now.wday == 5 || Time.now.wday == 1
      errors.add(:base, "No new users on Mondays.")
    end
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in

  def index
    @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
      flash[:notice] = 'Admin user created successfully'
      redirect_to(admin_users_path)
    else
      render('new')
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update_attributes(admin_user_params)
      flash[:notice] = 'Admin user update successfully.'
      redirect_to(admin_users_path)
    else
      render('edit')  #redirect them to the edit form again
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "Admin user destroyed successfully"
    redirect_to(admin_user_path)
  end

  private

  def admin_user_params
    #permit :password, but not :password_digest
    params.require(:@admin_user).permit(:first_name,:last_name,:email,:username,:password)
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/delete.html.erb
<h1>AdminUsers#delete</h1>
<p>Find me in app/views/admin_users/delete.html.erb</p>

app/views/admin_users/edit.html.erb
<h1>AdminUsers#edit</h1>
<p>Find me in app/views/admin_users/edit.html.erb</p>

app/views/admin_users/index.html.erb
<% @page_title = "All Admin Users" %>


<div class="admin_users index">
  <h2>Admin Users</h2>
  <!-- could just use subjects/new but url helper is better -->
  <%= link_to("Add New Admin User", new_admin_user_path, :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Subject ID</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
        <tr>
          <td><%= page.position %></td>
          <td><%= page.subject_id %></td>
          <td><%= page.name %></td>
          <td><%= page.permalink %></td>
          <!-- ternary opeator, short hand for if else statement. -->
          <td class="center"><%= page.visible ? 'Yes' : 'No' %></td>

          <td class="actions">
            <!-- using resourceful url helpers subject_path(subject)-->
            <%= link_to("Show", page_path(page), :class => 'action show') %>
            <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
            <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<h1>AdminUsers#new</h1>
<p>Find me in app/views/admin_users/new.html.erb</p>